version: 0.2
plaintext:
  JAVA_HOME: "/opt/jdk1.8.0_192"
phases:
  install:
    run-as: root
    runtime-versions:
      java: corretto8
    commands:
      - echo This is a installation
      - wget https://services.gradle.org/distributions/gradle-4.6-all.zip
      - unzip -d /opt/gradle gradle-4.6-all.zip
      - export PATH=$PATH:/opt/gradle/gradle-4.6/bin
      - touch /etc/profile.d/gradle.sh
      - chmod 755 /etc/profile.d/gradle.sh
      - echo "export PATH=$PATH:/opt/gradle/gradle-4.6/bin" >> /etc/profile.d/gradle.sh
  pre_build:
    commands:
      - echo This is a pre build
  build:
    commands:
      - echo Starting build `date`
      - echo Current directory is `pwd`
      - export PATH=$PATH:/opt/gradle/gradle-4.6/bin
      - whereis gradle
      - /opt/gradle/gradle-4.6/bin/gradle -version
      - /opt/gradle/gradle-4.6/bin/gradle build
  post_build:
    commands:
      - echo Build must be completed
artifacts:
  files:
    - '**/*'
  discard-paths: no
